### ISSUE TITLE
Secret management for GH Actions

### ISSUE THREAD

**Issue by muscariello** [cisco-open/hicn-sdk#22]
We need to have a bot account to manage secrets for the CICD.

**Comment by juliaferraioli** [comment]
Can you describe what you want to do? Why is a bot account the correct way to go?

**Comment by muscariello** [comment]
Hi @juliaferraioli  
we would need secret management for our CICD.  Forget the bot account if you have something else. That was just a suggestion to delegate to us the implementation.  Do you have something in place already that implements a secret store, scoped secrets, secret rotation, least privilege etc? 
Thanks

**Comment by detiber** [comment]
@muscariello Can you provide a bit more context on what you are looking to do?

What types of secrets are we talking about here? What purpose are they for?

Is this an external CI/CD system, or GitHub Actions? Is this for integrating with external services for build testing?

**Comment by muscariello** [comment]
We want to use github actions to build artifacts and store them in github packages. We do not want to use our accounts to manage token to trigger builds and move artifacts in the right places.

**Comment by muscariello** [comment]
I have added added my personal access token to this repo. @manang can you check if that's ok?
